---

- include: ../../erlapp.yml
  vars:
      name: just
      name_suffix: -full
      version: "{{service_version}}"
      data_dir: "{{just_data_dir}}"
      svc_name: "{{just_svc_name}}"

- name: Provision config
  template: src=app.config.j2
            dest=/opt/just-full-{{service_version}}/etc/app.config

- name: Provision config original
  template: src=app.config.j2
            dest=/opt/just-full-{{service_version}}/etc/app.config.original
