---
- name: Deploy Funnel/J3 services
  hosts: all
  roles:
  - {role: eng,             tags: ["eng"]}
  - {role: standalone_j3,   tags: ["standalone_j3"]}
  - {role: standalone_fun,  tags: ["standalone_fun"]}
  - {role: funnel,          tags: ["funnel"],          when: service_version is defined}
  - {role: just,            tags: ["just"],            when: service_version is defined}
