---
- name: Deploy Funnel/J3 services
  hosts: all
  sudo: true
  roles:
  - {role: funnel,       tags: ["funnel"],   when: service_version is defined}
  - {role: just,         tags: ["just"],     when: service_version is defined}